export const ICONS = [
    "directions_run",
    "menu_book",
    "laptop_mac",
    "self_improvement",
    "water_drop",
    "fitness_center",
    "code",
    "work",
    "bed",
    "local_dining",
    "savings",
    "palette",
    "music_note",
    "psychology",
    "home",
];

export const COLORS = [
    {
        name: "Blue",
        class: "bg-blue-500",
        textClass: "text-blue-600 dark:text-blue-400",
        bgClass: "bg-blue-100 dark:bg-blue-900/50",
        solidClass: "bg-blue-600 dark:bg-blue-400",
        borderClass: "border-blue-600 dark:border-blue-400",
        hoverBorderClass: "hover:border-blue-600 dark:hover:border-blue-400",
    },
    {
        name: "Purple",
        class: "bg-purple-500",
        textClass: "text-purple-600 dark:text-purple-400",
        bgClass: "bg-purple-100 dark:bg-purple-900/50",
        solidClass: "bg-purple-600 dark:bg-purple-400",
        borderClass: "border-purple-600 dark:border-purple-400",
        hoverBorderClass: "hover:border-purple-600 dark:hover:border-purple-400",
    },
    {
        name: "Orange",
        class: "bg-orange-500",
        textClass: "text-orange-600 dark:text-orange-400",
        bgClass: "bg-orange-100 dark:bg-orange-900/50",
        solidClass: "bg-orange-600 dark:bg-orange-400",
        borderClass: "border-orange-600 dark:border-orange-400",
        hoverBorderClass: "hover:border-orange-600 dark:hover:border-orange-400",
    },
    {
        name: "Teal",
        class: "bg-teal-500",
        textClass: "text-teal-600 dark:text-teal-400",
        bgClass: "bg-teal-100 dark:bg-teal-900/50",
        solidClass: "bg-teal-600 dark:bg-teal-400",
        borderClass: "border-teal-600 dark:border-teal-400",
        hoverBorderClass: "hover:border-teal-600 dark:hover:border-teal-400",
    },
    {
        name: "Emerald",
        class: "bg-emerald-500",
        textClass: "text-emerald-600 dark:text-emerald-400",
        bgClass: "bg-emerald-100 dark:bg-emerald-900/50",
        solidClass: "bg-emerald-600 dark:bg-emerald-400",
        borderClass: "border-emerald-600 dark:border-emerald-400",
        hoverBorderClass: "hover:border-emerald-600 dark:hover:border-emerald-400",
    },
    {
        name: "Rose",
        class: "bg-rose-500",
        textClass: "text-rose-600 dark:text-rose-400",
        bgClass: "bg-rose-100 dark:bg-rose-900/50",
        solidClass: "bg-rose-600 dark:bg-rose-400",
        borderClass: "border-rose-600 dark:border-rose-400",
        hoverBorderClass: "hover:border-rose-600 dark:hover:border-rose-400",
    },
    {
        name: "Indigo",
        class: "bg-indigo-500",
        textClass: "text-indigo-600 dark:text-indigo-400",
        bgClass: "bg-indigo-100 dark:bg-indigo-900/50",
        solidClass: "bg-indigo-600 dark:bg-indigo-400",
        borderClass: "border-indigo-600 dark:border-indigo-400",
        hoverBorderClass: "hover:border-indigo-600 dark:hover:border-indigo-400",
    },
    {
        name: "Cyan",
        class: "bg-cyan-500",
        textClass: "text-cyan-600 dark:text-cyan-400",
        bgClass: "bg-cyan-100 dark:bg-cyan-900/50",
        solidClass: "bg-cyan-600 dark:bg-cyan-400",
        borderClass: "border-cyan-600 dark:border-cyan-400",
        hoverBorderClass: "hover:border-cyan-600 dark:hover:border-cyan-400",
    },
];
